### ISSUE TITLE
translate 【maybe bug】

### ISSUE THREAD

**Issue by 7ancy** [ThaPwned/WCS#26]
wcs_centertell   Unable to use Chinese Translation

**Comment by 7ancy** [comment]
Characters cannot be displayed after translation

**Comment by ThaPwned** [comment]
> wcs_centertell Unable to use Chinese Translation

> Characters cannot be displayed after translation

This is not an issue with WCS but the ES Emulator instead. I've been trying to find where the issues lies but haven't been able to do so.

**Comment by 7ancy** [comment]
> > wcs_centertell Unable to use Chinese Translation
> 
> > Characters cannot be displayed after translation
> 
> This is not an issue with WCS but the ES Emulator instead. I've been trying to find where the issues lies but haven't been able to do so.

Do you have any alternatives to make it display my translation normally, I am using the race of https://github.com/ManifestManah/Racepack-Standard

**Comment by ThaPwned** [comment]
> Do you have any alternatives to make it display my translation normally, I am using the race of https://github.com/ManifestManah/Racepack-Standard

A thing you could do (if you're comfortable with coding a bit yourself) is to add the translations to the `resource/source-python/translations/wcs/strings.ini` file (create it if it doesn't exist), and then use wcs_xtell (instead of es_tell) and wcs_xcentertell (instead of es_centertell).

So instead of (taking Archmage Proudmore as an example):
`es wcs_centertell event_var(userid) event_var(es_attackername) struck you with his earthquake!`
You change it to:
`es wcs_xcentertell event_var(userid) archmage_proudmore_shake_victim name event_var(es_attackername)`
The `strings.ini` file would then look like this:
```ini
[archmage_proudmore_shake_victim]
  en = "$name struck you with his earthquake!"
  zh-cn = "$name 震撼了你!"
```
(my apologize if I've completely butchered the translation - Google Translate's fault)
`archmage_proudmore_shake_victim` is the text `wcs_xcentertell` (and `wcs_xtell` for that matter) searches for, so make sure it's unique to that race as well as skill (and for multiple messages in same skill, make them unique as I've done: Added `_victim` for the victim's message). The `name` part of the command is a key it searches for in the translations. It's then being replaced by the next argument which is `event_var(es_attackername)`.

**Comment by 7ancy** [comment]
> > 你有没有别的办法让它显示我的翻译，我用的是[Https://github.com/ManifestManah/Racepack-Standard](https://github.com/ManifestManah/Racepack-Standard)
> 
> 您可以做的一件事(如果您对自己编写代码很满意的话)是将翻译添加到`resource/source-python/translations/wcs/strings.ini`文件(如果它不存在的话创建它)，然后使用wcs_xtelt(而不是es_telt)和wcs_x心TEL(而不是es_中心语)。
> 
> 因此，不要(以大法师Proudmore为例)：
> `es wcs_centertell event_var(userid) event_var(es_attackername) struck you with his earthquake!`
> 你把它改为：
> `es wcs_xcentertell event_var(userid) archmage_proudmore_shake_victim name event_var(es_attackername)`
> 这个`strings.ini`然后，文件将如下所示：
> 
> ```ini
> [archmage_proudmore_shake_victim]
>   en = "$name struck you with his earthquake!"
>   zh-cn = "$name 震撼了你!"
> ```
> 
> (如果我把翻译全毁了--谷歌翻译的错误，我很抱歉)
> `archmage_proudmore_shake_victim`是文本`wcs_xcentertell`(和`wcs_xtell`)搜索，所以确保它对该种族和技能都是独一无二的(对于同一技能中的多条消息，让它们像我所做的那样独一无二：`_victim`受害者的信息)。这个`name`命令的一部分是它在翻译中搜索的键。然后，它被下一个参数所取代，这个参数是`event_var(es_attackername)`.

Thank you for your method. I'll try
