### ISSUE TITLE
[REQUEST] Old raceinfo/skillinfo system

### ISSUE THREAD

**Issue by NosferatuJoe** [ThaPwned/WCS#70]
A lot of players in my community are requesting the old raceinfo/skillinfo where's the skill description would be beneath the skill name. That way you don't always have to "click" on skills to see what they do. I think the same issue persists in shopmenu but I haven't checked yet.

This makes browsing races and viewing their skills&info a lot easier than it is now.

**Comment by ManifestManah** [comment]
I agree, this feature has been asked about a couple of times on my server as well back when it had players as a lot of players dislike the current way where they have to read up on the skills individually.
Maybe an option in the config file could be added where the server owners can choose which of the two ways to use, depending on their individual preferences?

**Comment by Xiazee** [comment]
We could probably get away with displaying at least a short description of the skills in the raceinfo menu. Perhaps selecting a skill could then expand that skill description on the same page, rather than opening a separate menu for that.

In terms of the character limit, we could save some by reducing or removing the dividing characters.

It might also be interesting to look into whether it is possible to use a HudMsg to display additional information next to the radio menu. As far as I know it's used to display the messages in the center of the screen, but should also be able to be positioned elsewhere.

**Comment by ThaPwned** [comment]
This is implemented in 193578c8343dcbe0312d52898511810aee034b05. This might be subject to change if there's issues with utf-8 characters.
